### ISSUE TITLE
[BUG] Create certification campaign check for option field correlated_status

### ISSUE THREAD

**Issue by niranjan-pontis** [sailpoint-oss/python-sdk#27] opened 2024-07-19 01:00 UTC
Trying to create a search campaign using SDK however I keep getting validation error for an option field correlated_status. It is defined as a type dict. So it needs some value of type dict but the validation code then checks against enum so overall the validation fails. I was able to work around the problem by changing the type for correlated_status to StrictStr. It is an optional field but it looks like because of dict type it has become mandatory?

**Comment by niranjan-pontis** [comment] 2024-07-19 01:03
Here is the error if you don't pass the correlated status in Campaign

correlatedStatus
  Input should be a valid dictionary [type=dict_type, input_value='CORRELATED', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/dict_type
    
If you pass it in dict format then the error is for allowed values


Value error, must be one of enum values ('CORRELATED', 'UNCORRELATED') [type=value_error, input_value={'type': 'dict_type', 'in...}, 'input_type': 'list'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error

I was able to make it work by changing the type of that field to str in campaign.py

correlated_status: Optional[StrictStr]

**Comment by niranjan-pontis** [comment] 2024-07-19 01:04
The issue appears to be same as reported in #21

**Comment by tyler-mairose-sp** [comment] 2024-08-27 18:25
Hey @niranjan-pontis, you are correct that this is a duplicate of #21. This has been fixed in https://github.com/sailpoint-oss/python-sdk/commit/59b096ba03213367f492f2ed0040b44727ef08a7

**Closed by tyler-mairose-sp** 2024-08-27 18:25 UTC
